config/routes.rb
Rails.application.routes.draw do
  resources :parks, only: [:show] do
    resources :dinosaurs, only: [:new, :create]
  end
  resources :dinosaurs, only: :destroy do
    resources :meals, only: [:new, :create]
  end
  resources :meals, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
  belongs_to :park
  has_many :meals, dependent: :destroy
  has_many :foods, through: :meals
  SPECIES = ['t-rex', 'pterydactyl', 'triceritops', 'brontisaurus', 'velociraptor', 'stegasaurus', 'chicken']
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :meals
  has_many :dinosaurs, through: :meals
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :dinosaur
  belongs_to :food
  validates :dinosaur_id, uniqueness: { scope: :food_id }
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :dinosaurs, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end


# park.dinosaurs

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  def new
    @park = Park.find(params[:park_id])
    @dinosaur = Dinosaur.new
  end

  def create
    @dinosaur = Dinosaur.new(dinosaur_params)
    @park = Park.find(params[:park_id])
    @dinosaur.park = @park
    if @dinosaur.save
      redirect_to park_path(@park)
    else
      render :new # show the form
    end
  end

  def destroy
    @dinosaur = Dinosaur.find(params[:id])
    @dinosaur.destroy
    redirect_to park_path(@dinosaur.park)
  end

  private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :species)
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_dinosaur, only: [:new, :create]
  def new
    @meal = Meal.new # meals_path
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.dinosaur = @dinosaur
    if @meal.save
      redirect_to park_path(@dinosaur.park)
    else
      render :new
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to park_path(@meal.dinosaur.park)
  end

  private

  def meal_params
    params.require(:meal).permit(:food_id)
  end

  def set_dinosaur
    @dinosaur = Dinosaur.find(params[:dinosaur_id])
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  def index
    @parks = Park.all
  end

  # GET /parks/1
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  def create
    @park = Park.new(park_params)

    if @park.save
      redirect_to @park, notice: 'Park was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /parks/1
  def update
    if @park.update(park_params)
      redirect_to @park, notice: 'Park was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /parks/1
  def destroy
    @park.destroy
    redirect_to parks_url, notice: 'Park was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def park_params
      params.require(:park).permit(:name, :banner_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/dinosaurs/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-3">
    <div class="col-6">
      <h1>Add Dino to <%= @park.name %></h1>
      <%= simple_form_for [@park, @dinosaur] do |f| %>
        <%= f.input :name %>
        <%= f.input :species, collection: Dinosaur::SPECIES, input_html: {allow_blank: false } %>
        <%= f.submit class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>JurassicPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col col-sm-6">
      <h1>Add a meal for <%= @dinosaur.name %></h1>
      <%= simple_form_for [@dinosaur, @meal] do |f| %>
        <%= f.association :food, collection: Food.where.not(id: @dinosaur.foods) %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/parks/_form.html.erb
<%= simple_form_for(@park) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%= park.name %></td>
        <td><%= park.banner_url %></td>
        <td><%= link_to 'Show', park %></td>
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Park', new_park_path %>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @park.banner_url %>);">
  <div class="container">
    <h1><%= @park.name %></h1>
    <%= link_to "Add Dino", new_park_dinosaur_path(@park), class: "btn btn-danger"  %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="cards mt-3">
      <% @park.dinosaurs.each do  |dinosaur| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= dinosaur.image_url %>)">
          <div class="card-foods">
            <% dinosaur.meals.each do |meal| %>
              <span><%= link_to meal.food.name, meal_path(meal), method: :delete, data: {confirm: "Hey i know it's weird, but do you want to delete this food?"} %></span>
            <% end %>
          </div>
          <%= dinosaur.name %>
          <br>
          <%= dinosaur.species %>
          <small>
            <%= link_to new_dinosaur_meal_path(dinosaur), class: "btn-chicken" do %>
              <i class="fas fa-drumstick-bite"></i>
            <% end %>
          </small>
          <%= link_to dinosaur_path(dinosaur), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link " do %>
            <i class="fas fa-meteor"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>